version: '3'
services:
  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile.dev
      target: development
    volumes:
      - ./nextjs:/app  # Mount local directory for live reloading
      - /app/node_modules
    environment:
      - NODE_ENV=development