version: '3'

services:
  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile.prod
      target: production  # Default to production if NODE_ENV is not provided
    ports:
      - "3000:3000"
    volumes:
      - nextjs_data:/app/data  # Only mount the data volume in production
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  python-service:
    build:
      context: ./python_service
      dockerfile: Dockerfile
    volumes:
      - nextjs_data:/app/data
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - db
    restart: unless-stopped

  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  nextjs_data:
  pgdata:
